### ISSUE TITLE
add an FAQ telling folks how they can validate their yml

### ISSUE THREAD

**Issue by manishas** [Shippable/docsv2#115]
Point them to - 
http://yaml-online-parser.appspot.com/
http://www.yamllint.com/

**Comment by lekhab** [comment]
This FAQ already includes a line on validating the YML.

http://docs.shippable.com/faq/#i-have-enabled-my-repository-and-committed-code-but-my-build-doesnt-start-what-could-be-wrong

Added another FAQ here:
http://docs.shippable.com/faq/#how-can-i-validate-my-shippable-yml

Closing.
