### ISSUE TITLE
Document slack integration

### ISSUE THREAD

**Issue by rageshkrishna** [Shippable/docsv2#128]
We can use this as a reference: https://github.com/Shippable/pm/wiki/How-to:-Set-up-Slack-integration-for-build-notifications

https://github.com/Shippable/pm/issues/4138

**Comment by manishas** [comment]
@lekhab can you pick this up please?

**Comment by manishas** [comment]
@lekhab this is now in prod. can you send a PR for docs so i can merge? Thanks
