### ISSUE TITLE
How To dropdown too long

### ISSUE THREAD

**Issue by kailevy** [Shippable/docsv2#138]
![image](https://cloud.githubusercontent.com/assets/9276347/9232627/99d5bcfa-40e3-11e5-8891-c960d8d67be5.png)

There is another entry that I can't access because the dropdown is too long and will not scroll.

**Comment by xdothackerx** [comment]
Will figure something out! Thanks for finding this.

**Comment by xdothackerx** [comment]
@kailevy Next time, post a bug in PM so I see the issue sooner, eh? ;D

**Comment by manishas** [comment]
@kailevy please open bugs in pm repo and not here.

**Comment by xdothackerx** [comment]
@manishas Would you still like me to work on this now, or should I wait till a bug is opened in PM?

**Comment by manishas** [comment]
You can open up the bug in pm, link this one and reopen this and work on it :)

**Comment by xdothackerx** [comment]
Created a PM bug issue.

https://github.com/Shippable/pm/issues/4503

**Comment by xdothackerx** [comment]
Likely will implement the solution found here http://stackoverflow.com/questions/19227496/scrollable-menu-with-bootstrap-3-menu-expanding-its-container-when-it-should-n tomorrow morning. Going to wind down for today to try to defog my brain a bit.
