### ISSUE TITLE
We need sample code for each GCR matrix scenario

### ISSUE THREAD

**Issue by avinci** [Shippable/docsv2#14]
https://github.com/Shippable/pm/issues/3451

**Comment by manishas** [comment]
please specify exactly what you need.

there is no 'code', just settings. all settings have been described.

**Comment by lekhab** [comment]
https://github.com/Shippable/pm/issues/3364

**Comment by avinci** [comment]
closing this. We need to think about this holistically. When there is code changing, then we need separate repos. I.e. a new code path, Dockerfile etc. But if its just making the same code behave differently by settings changing, then we need only 1 sample code.

e.g. Docker push to docker hub or GCR is the same repo cos there is not change in the repo. But DockerBuild from docker file is technically different repos as its using different Dockerfiles.
