### ISSUE TITLE
Build badges are broken

### ISSUE THREAD

**Issue by bhargav3** [Shippable/docsv2#179]
I'm seeing the badge but it says "Build inaccessible"

Example: [![Build Status](https://img.shields.io/shippable/56af0b6a1895ca44747311fc/master.svg)](https://app.shippable.com/projects/56af0b6a1895ca44747311fc)

**Comment by manishas** [comment]
@bhargav3 this is not a documentation issue. Your build badges will be available as soon as your subscriptions are migrated to the new build system. ETA is < 72 hours.

**Comment by bhargav3** [comment]
Oops! I see. Thank you :+1:
