### ISSUE TITLE
Add section to describe deployment to beanstalk

### ISSUE THREAD

**Issue by manishas** [Shippable/docsv2#204]
We need the following:

Under Integrations, we need a menu item called PaaS/IaaS providers
For now, we will only have Amazon Elastic Beanstalk. Add instructions to create an account integration.

In CI->Configuring your build, add a section - Configuring deployments to PaaS/IaaS
Under it, add Amazon Elastic Beanstalk
Describe how to deploy code to EB - Add integration to project settings, and yml config.

**Comment by abhijitkini** [comment]
- [ ] Deploying code to EB under CI. COMPLETE

- [ ] Instructions to create EB account integration under Integrations. Working on it. Will be done by EOD

**Comment by abhijitkini** [comment]
Goal for EOD Wednesday:
- [ ] Docker based deployments to EB under CI

**Comment by abhijitkini** [comment]
Both Source Code & Docker deployments to EB documentation are complete. Closing the issue.
