### ISSUE TITLE
update the documentation to reflect the usage of language: none tag in yml

### ISSUE THREAD

**Issue by kanthchandra** [Shippable/docsv2#221]
from https://github.com/Shippable/support/issues/2385

**Comment by abhijitkini** [comment]
The documentation has been updated to reflect the none tag in the shippable.yml reference (http://docs.shippable.com/ci_configure/#specifying-language-and-runtime) & also in the unsupported languages (http://docs.shippable.com/ci_configure/#unsupported_languages)
