### ISSUE TITLE
Update docs with updated graphics

### ISSUE THREAD

**Issue by ttrahan** [Shippable/docsv2#263]
https://github.com/Shippable/pm/issues/5804

Update Docs with latest Shippable graphics/workflow representations

**Comment by ttrahan** [comment]
@abhijitkini : please confirm date to complete this

**Comment by abhijitkini** [comment]
Plan for Wednesday:
Complete the updates of images in Docs today.

**Comment by ttrahan** [comment]
https://github.com/Shippable/docsv2/pull/267
