### ISSUE TITLE
Broken url on aws

### ISSUE THREAD

**Issue by sydhenry** [Shippable/docsv2#291]
Not sure where the source is but on this [page](https://app.shippable.com/integrations/aws.html), the "Getting Started" section has this link:
[Setting up an AWS instance as a Dedicated Host for CI](http://docs.shippable.com//ci_byoh/)

The link should have the extra `/` removed and be `http://docs.shippable.com/ci_byoh/`. The link above and below the one mentioned are correct

edit:

actual the page link is going to [Running Builds On Your Own Machines (BYOH)
](http://docs.shippable.com/ci_byoh/) so that link is wrong anyways.

**Comment by abhijitkini** [comment]
the URL has been fixed.
