### ISSUE TITLE
Document if/how to work with github private repos

### ISSUE THREAD

**Issue by pjz** [Shippable/docsv2#304]
There's nothing saying if shippable will or won't or how to work with private github repos.

**Comment by manishas** [comment]
Yes shippable works with private repos. You will need to turn on access to private repos by going to Account settings (gear icon on top navbar),going to the Git identities section and clicking Enable for private repos

**Comment by pjz** [comment]
Ah! Okay; it was a bit hidden.  You might hilight it a bit in the docs somewhere, maybe under 'integrations'.

**Comment by abhijitkini** [comment]
Documents updated: 
http://docs.shippable.com/int_scm/
http://docs.shippable.com/ci_faq/#why-cant-i-see-some-of-my-repositories-in-my-shippable-account
