### ISSUE TITLE
[cs1] Update documentation on status monitoring

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/docsv2#322]
https://github.com/Shippable/pm/issues/5899

**Comment by abhijitkini** [comment]
Docs to be updated:

- [ ] http://docs.shippable.com/gs_supported/
- [ ] Create a new doc under CI called "Status Monitoring". It should include info on: 
   - Overview of the 'Status' page
   - How to subscribe for updates (Atom/RSS feed)
   - Resources to monitor when there is a service outage (Status page, twitter, support issues)
- [ ] http://docs.shippable.com/ci_faq/ (Will be updated once there are FAQs on status monitoring/notifications)

**Comment by manishas** [comment]
gs_supported doesn't need to be updated. this is our status page, and not a language or tool that we support.

**Comment by manishas** [comment]
i have updated a section in ci_configure with the status page. i am not sure where else we can out it.... maybe in the overview section.
