### ISSUE TITLE
Update docs for new hub integration type

### ISSUE THREAD

**Issue by ttrahan** [Shippable/docsv2#339]
Update docs with instructions for adding a Docker Trusted Registry hub integration.

Page: http://docs.shippable.com/ci_configure/#pulling-your-ci-image-from-a-docker-registry

Section:
"In the type tag, enter the type of registry. Options are docker for Docker Hub, gcr for Google container registry, quay.io for Quay.io, ecr for Amazon EC2 Container registry, and private docker registry for a self hosted private registry."

**Comment by abhijitkini** [comment]
- [ ] update http://docs.shippable.com/ci_docker/#docker-registries-integration

**Comment by manishas** [comment]
this is an orphan issue. closing.

**Comment by abhijitkini** [comment]
https://github.com/Shippable/pm/issues/5968
Attached to a PM issue.

**Comment by abhijitkini** [comment]
Closing issue
