### ISSUE TITLE
[cs4] Update docs on conditional build triggering using webhook type

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/docsv2#349]
https://github.com/Shippable/pm/issues/5969

Docs to be updated:
- [x] http://docs.shippable.com/ci_projects/
    - Between 'code coverage badges' and 'dashboard settings' sections

http://docs.shippable.com/ci_overview/#build-trigger has already been updated.

**Comment by manishas** [comment]
once we update the ci_projects page, we should include a link to there from the build_trigger section saying you can configure which events trigger builds.
