### ISSUE TITLE
File deployment docs

### ISSUE THREAD

**Issue by trriplejay** [Shippable/docsv2#603]
Shippable/pm#7036

- [x] how to add a custom 'cluster' via account integration with one or more machines
- [x] new resource type 'file' with explanation of how to declare it in yml, and a list of supported providers (only artifactory right now)
- [x] how to create and deploy a file type resource to this custom cluster (a sample project would be great, much like our 'connecting ci to pipelines' example, but using a file instead of an image)
- [x] may want to update existing pages for 'manfiest', 'deploy', 'release', etc to mention that they can be used with file-type resources (not just images)

**Comment by scriptnull** [comment]
## Update:
- Raised a PR for some parts of the docs.
- Will post a draft after clearing somethings or in best case, will open a docsv2 PR for it.

**Comment by scriptnull** [comment]
All documentation updates are merged. Sample project ( https://github.com/shippableSamples/sample_pipelines ) is updated with the sample yml demonstrating this functionality.

Hence, closing this.
