### ISSUE TITLE
Style Docs: Fix the FAQ bar overflow

### ISSUE THREAD

**Issue by lekhab** [Shippable/docsv2#62]
https://github.com/Shippable/pm/issues/3594

**Comment by lekhab** [comment]
Sam will pick this up after she's done with her current tasks

**Comment by xdothackerx** [comment]
What is the FAQ bar overflow? Do you have a screen? :O I can't remember if you showed me this one.

**Comment by lekhab** [comment]
I don't see this happening now. I guess the stickiness was the solution. closing.
