### ISSUE TITLE
7664 docs: Re-make triggering jobs graphic for jobs overview page

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/docsv2#656]
https://github.com/Shippable/pm/issues/7664

This graphic still shows the old context menu from the SPOG:

![jobsoverview](https://cloud.githubusercontent.com/assets/7757711/22231425/608dd1f6-e198-11e6-8722-295f9e5976a1.png)

It needs to be updated with a new right-click context menu, like this one:
![dv-manrightclickmenu](https://cloud.githubusercontent.com/assets/7757711/22231474/b3be0c88-e198-11e6-9054-02b8cd4178f6.png)

**Comment by manishas** [comment]
this is complete.closing.
